[2022-11-23T06:28:09.448+0000] {processor.py:154} INFO - Started process (PID=42) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:28:09.449+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:28:09.450+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:28:09.450+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:28:10.240+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:28:10.239+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:28:10.241+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:28:10.282+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.837 seconds
[2022-11-23T06:28:40.945+0000] {processor.py:154} INFO - Started process (PID=98) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:28:40.948+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:28:40.949+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:28:40.948+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:28:41.223+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:28:41.222+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:28:41.224+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:28:41.249+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.307 seconds
[2022-11-23T06:29:12.023+0000] {processor.py:154} INFO - Started process (PID=163) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:29:12.024+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:29:12.025+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:29:12.025+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:29:12.326+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:29:12.322+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:29:12.327+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:29:12.383+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.364 seconds
[2022-11-23T06:29:43.027+0000] {processor.py:154} INFO - Started process (PID=219) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:29:43.029+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:29:43.030+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:29:43.030+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:29:43.228+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:29:43.228+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:29:43.229+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:29:43.257+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.236 seconds
[2022-11-23T06:30:13.500+0000] {processor.py:154} INFO - Started process (PID=282) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:30:13.501+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:30:13.502+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:30:13.502+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:30:13.750+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:30:13.749+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:30:13.751+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:30:13.782+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.287 seconds
[2022-11-23T06:30:44.167+0000] {processor.py:154} INFO - Started process (PID=336) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:30:44.168+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:30:44.169+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:30:44.169+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:30:44.363+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:30:44.362+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:30:44.364+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:30:44.401+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.237 seconds
[2022-11-23T06:31:14.728+0000] {processor.py:154} INFO - Started process (PID=403) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:31:14.730+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:31:14.731+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:31:14.730+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:31:14.956+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:31:14.953+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:31:14.956+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:31:14.982+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.257 seconds
[2022-11-23T06:31:45.485+0000] {processor.py:154} INFO - Started process (PID=467) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:31:45.486+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:31:45.487+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:31:45.487+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:31:45.801+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:31:45.799+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:31:45.802+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:31:45.857+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.376 seconds
[2022-11-23T06:32:16.337+0000] {processor.py:154} INFO - Started process (PID=524) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:32:16.338+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:32:16.339+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:32:16.339+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:32:16.535+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:32:16.534+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:32:16.536+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:32:16.562+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.229 seconds
[2022-11-23T06:32:47.373+0000] {processor.py:154} INFO - Started process (PID=589) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:32:47.374+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:32:47.375+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:32:47.375+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:32:47.528+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:32:47.527+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:32:47.528+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:32:47.553+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.184 seconds
[2022-11-23T06:33:18.096+0000] {processor.py:154} INFO - Started process (PID=646) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:33:18.100+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:33:18.101+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:33:18.101+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:33:18.265+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:33:18.264+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:33:18.265+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:33:18.294+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.202 seconds
[2022-11-23T06:33:48.747+0000] {processor.py:154} INFO - Started process (PID=710) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:33:48.748+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:33:48.750+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:33:48.749+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:33:48.904+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:33:48.903+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:33:48.904+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:33:48.928+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.184 seconds
[2022-11-23T06:34:18.977+0000] {processor.py:154} INFO - Started process (PID=776) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:34:18.984+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:34:18.985+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:34:18.985+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:34:19.185+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:34:19.184+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:34:19.185+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:34:19.214+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.241 seconds
[2022-11-23T06:34:49.647+0000] {processor.py:154} INFO - Started process (PID=834) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:34:49.648+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:34:49.649+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:34:49.649+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:34:49.819+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:34:49.819+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:34:49.820+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:34:49.841+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.197 seconds
[2022-11-23T06:35:20.011+0000] {processor.py:154} INFO - Started process (PID=899) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:35:20.012+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:35:20.013+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:35:20.013+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:35:20.178+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:35:20.177+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:35:20.178+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:35:20.222+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.215 seconds
[2022-11-23T06:35:50.432+0000] {processor.py:154} INFO - Started process (PID=954) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:35:50.433+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:35:50.434+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:35:50.434+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:35:50.597+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:35:50.596+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:35:50.597+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:35:50.620+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.192 seconds
[2022-11-23T06:36:21.086+0000] {processor.py:154} INFO - Started process (PID=1022) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:36:21.087+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:36:21.088+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:36:21.087+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:36:21.240+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:36:21.239+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:36:21.240+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:36:21.262+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.179 seconds
[2022-11-23T06:36:51.876+0000] {processor.py:154} INFO - Started process (PID=1080) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:36:51.877+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:36:51.878+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:36:51.878+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:36:52.091+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:36:52.090+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:36:52.092+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:36:52.133+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.262 seconds
[2022-11-23T06:37:22.893+0000] {processor.py:154} INFO - Started process (PID=1144) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T06:37:22.894+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T06:37:22.896+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:37:22.895+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:37:23.066+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:37:23.065+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:37:23.066+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T06:37:23.090+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.200 seconds
[2022-11-23T08:45:02.958+0000] {processor.py:154} INFO - Started process (PID=42) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:45:02.972+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:45:02.973+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:45:02.972+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:45:03.486+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:45:03.481+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:45:03.489+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:45:03.541+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.587 seconds
[2022-11-23T08:45:34.288+0000] {processor.py:154} INFO - Started process (PID=99) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:45:34.290+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:45:34.292+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:45:34.291+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:45:34.553+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:45:34.552+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:45:34.553+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:45:34.583+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.304 seconds
[2022-11-23T08:46:05.348+0000] {processor.py:154} INFO - Started process (PID=156) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:46:05.350+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:46:05.351+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:46:05.350+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:46:05.713+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:46:05.706+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:46:05.714+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:46:05.756+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.414 seconds
[2022-11-23T08:46:36.300+0000] {processor.py:154} INFO - Started process (PID=221) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:46:36.303+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:46:36.303+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:46:36.303+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:46:36.522+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:46:36.521+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:46:36.522+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:46:36.546+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.250 seconds
[2022-11-23T08:47:07.146+0000] {processor.py:154} INFO - Started process (PID=278) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:47:07.147+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:47:07.148+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:47:07.148+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:47:07.343+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:47:07.342+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:47:07.344+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:47:07.366+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.224 seconds
[2022-11-23T08:47:37.419+0000] {processor.py:154} INFO - Started process (PID=345) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:47:37.420+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:47:37.421+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:47:37.421+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:47:37.652+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:47:37.651+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:47:37.652+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:47:37.688+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.272 seconds
[2022-11-23T08:48:08.532+0000] {processor.py:154} INFO - Started process (PID=401) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:48:08.533+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:48:08.534+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:48:08.534+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:48:08.708+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:48:08.707+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:48:08.708+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:48:08.738+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.211 seconds
[2022-11-23T08:48:38.818+0000] {processor.py:154} INFO - Started process (PID=465) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:48:38.819+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:48:38.820+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:48:38.820+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:48:39.117+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:48:39.115+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:48:39.117+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:48:39.152+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.338 seconds
[2022-11-23T08:49:09.493+0000] {processor.py:154} INFO - Started process (PID=521) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:49:09.496+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:49:09.497+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:49:09.496+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:49:09.741+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:49:09.739+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:49:09.741+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:49:09.766+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.278 seconds
[2022-11-23T08:49:39.827+0000] {processor.py:154} INFO - Started process (PID=585) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:49:39.829+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:49:39.830+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:49:39.829+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:49:40.251+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:49:40.250+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:49:40.252+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:49:40.287+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.464 seconds
[2022-11-23T08:50:18.258+0000] {processor.py:154} INFO - Started process (PID=622) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:50:18.268+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:50:18.270+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:50:18.269+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:50:18.557+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:50:18.555+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:50:18.558+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:50:18.600+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.347 seconds
[2022-11-23T08:50:49.162+0000] {processor.py:154} INFO - Started process (PID=678) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:50:49.163+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:50:49.164+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:50:49.163+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:50:49.426+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:50:49.423+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:50:49.426+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:50:49.467+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.309 seconds
[2022-11-23T08:51:20.282+0000] {processor.py:154} INFO - Started process (PID=734) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:51:20.288+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:51:20.290+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:51:20.289+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:51:20.567+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:51:20.566+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:51:20.567+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:51:20.592+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.316 seconds
[2022-11-23T08:51:24.572+0000] {processor.py:154} INFO - Started process (PID=757) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:51:24.573+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:51:24.574+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:51:24.574+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:51:24.824+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:51:24.820+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:51:24.824+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:51:24.872+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.305 seconds
[2022-11-23T08:51:55.113+0000] {processor.py:154} INFO - Started process (PID=811) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:51:55.114+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:51:55.115+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:51:55.115+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:51:55.398+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:51:55.396+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:51:55.399+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:51:55.470+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.362 seconds
[2022-11-23T08:52:25.562+0000] {processor.py:154} INFO - Started process (PID=866) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:52:25.568+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:52:25.569+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:52:25.569+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:52:26.041+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:52:26.039+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:52:26.042+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:52:26.080+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.529 seconds
[2022-11-23T08:52:56.122+0000] {processor.py:154} INFO - Started process (PID=922) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:52:56.123+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:52:56.124+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:52:56.124+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:52:56.297+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:52:56.296+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:52:56.297+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:52:56.322+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.204 seconds
[2022-11-23T08:53:26.594+0000] {processor.py:154} INFO - Started process (PID=975) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:53:26.596+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:53:26.597+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:53:26.597+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:53:26.762+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:53:26.761+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:53:26.762+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:53:26.787+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.198 seconds
[2022-11-23T08:53:56.866+0000] {processor.py:154} INFO - Started process (PID=1036) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:53:56.871+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:53:56.872+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:53:56.872+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:53:57.228+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:53:57.227+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:53:57.229+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:53:57.282+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.420 seconds
[2022-11-23T08:54:27.625+0000] {processor.py:154} INFO - Started process (PID=1091) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:54:27.628+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:54:27.629+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:54:27.629+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:54:27.813+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:54:27.812+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:54:27.813+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:54:27.838+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.216 seconds
[2022-11-23T08:54:58.065+0000] {processor.py:154} INFO - Started process (PID=1154) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:54:58.066+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:54:58.067+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:54:58.067+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:54:58.658+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:54:58.657+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:54:58.658+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:54:58.745+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.684 seconds
[2022-11-23T08:55:29.574+0000] {processor.py:154} INFO - Started process (PID=1212) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:55:29.575+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:55:29.576+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:55:29.576+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:55:29.822+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:55:29.821+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:55:29.823+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:55:29.867+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.297 seconds
[2022-11-23T08:55:59.996+0000] {processor.py:154} INFO - Started process (PID=1277) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:56:00.000+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:56:00.001+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:56:00.001+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:56:00.780+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:56:00.776+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:56:00.780+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:56:00.824+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.844 seconds
[2022-11-23T08:56:31.291+0000] {processor.py:154} INFO - Started process (PID=1333) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:56:31.293+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:56:31.295+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:56:31.295+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:56:31.473+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:56:31.472+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:56:31.474+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:56:31.498+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.215 seconds
[2022-11-23T08:57:01.759+0000] {processor.py:154} INFO - Started process (PID=1391) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:57:01.760+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:57:01.761+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:57:01.761+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:57:02.135+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:57:02.134+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:57:02.135+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:57:02.222+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.467 seconds
[2022-11-23T08:57:33.074+0000] {processor.py:154} INFO - Started process (PID=1454) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:57:33.076+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:57:33.077+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:57:33.077+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:57:33.247+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:57:33.246+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:57:33.248+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:57:33.271+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.202 seconds
[2022-11-23T08:58:03.820+0000] {processor.py:154} INFO - Started process (PID=1509) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:58:03.821+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:58:03.822+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:58:03.822+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:58:04.198+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:58:04.196+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:58:04.198+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:58:04.263+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.447 seconds
[2022-11-23T08:58:34.375+0000] {processor.py:154} INFO - Started process (PID=1564) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:58:34.378+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:58:34.380+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:58:34.380+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:58:34.952+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:58:34.948+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:58:34.953+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:58:35.016+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.646 seconds
[2022-11-23T08:59:05.758+0000] {processor.py:154} INFO - Started process (PID=1619) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:59:05.763+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:59:05.765+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:59:05.764+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:59:06.163+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:59:06.162+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:59:06.164+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:59:06.218+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.477 seconds
[2022-11-23T08:59:36.547+0000] {processor.py:154} INFO - Started process (PID=1675) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T08:59:36.548+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T08:59:36.550+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:59:36.549+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:59:36.902+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:59:36.898+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:59:36.903+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T08:59:36.957+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.416 seconds
[2022-11-23T09:00:07.330+0000] {processor.py:154} INFO - Started process (PID=1732) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:00:07.332+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:00:07.333+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:00:07.332+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:00:07.561+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:00:07.560+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:00:07.562+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:00:07.603+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.278 seconds
[2022-11-23T09:00:37.748+0000] {processor.py:154} INFO - Started process (PID=1796) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:00:37.752+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:00:37.753+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:00:37.753+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:00:38.005+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:00:38.004+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:00:38.006+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:00:38.072+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.334 seconds
[2022-11-23T09:01:08.230+0000] {processor.py:154} INFO - Started process (PID=1852) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:01:08.231+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:01:08.232+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:01:08.232+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:01:08.530+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:01:08.514+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:01:08.531+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:01:08.635+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.410 seconds
[2022-11-23T09:01:39.581+0000] {processor.py:154} INFO - Started process (PID=1908) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:01:39.588+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:01:39.589+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:01:39.589+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:01:39.880+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:01:39.879+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:01:39.881+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:01:39.921+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.357 seconds
[2022-11-23T09:02:10.285+0000] {processor.py:154} INFO - Started process (PID=1970) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:02:10.286+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:02:10.288+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:02:10.288+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:02:10.627+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:02:10.621+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:02:10.627+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:02:10.706+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.426 seconds
[2022-11-23T09:02:40.891+0000] {processor.py:154} INFO - Started process (PID=2026) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:02:40.908+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:02:40.909+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:02:40.909+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:02:41.505+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:02:41.483+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:02:41.506+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:02:41.556+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.701 seconds
[2022-11-23T09:03:11.656+0000] {processor.py:154} INFO - Started process (PID=2084) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:03:11.658+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:03:11.659+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:03:11.659+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:03:11.906+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:03:11.905+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:03:11.907+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:03:11.936+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.284 seconds
[2022-11-23T09:03:42.249+0000] {processor.py:154} INFO - Started process (PID=2138) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:03:42.250+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:03:42.251+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:03:42.251+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:03:42.475+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:03:42.474+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:03:42.476+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:03:42.507+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.262 seconds
[2022-11-23T09:04:13.516+0000] {processor.py:154} INFO - Started process (PID=2202) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:04:13.518+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:04:13.519+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:04:13.519+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:04:13.804+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:04:13.803+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:04:13.805+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:04:13.834+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.322 seconds
[2022-11-23T09:04:44.176+0000] {processor.py:154} INFO - Started process (PID=2256) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:04:44.177+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:04:44.178+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:04:44.178+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:04:44.359+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:04:44.358+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:04:44.360+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:04:44.388+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.216 seconds
[2022-11-23T09:05:14.663+0000] {processor.py:154} INFO - Started process (PID=2312) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:05:14.665+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:05:14.666+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:05:14.665+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:05:14.950+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:05:14.949+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:05:14.951+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:05:14.980+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.325 seconds
[2022-11-23T09:05:45.203+0000] {processor.py:154} INFO - Started process (PID=2368) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:05:45.211+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:05:45.212+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:05:45.212+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:05:45.885+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:05:45.883+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:05:45.886+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:05:46.051+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.858 seconds
[2022-11-23T09:06:16.398+0000] {processor.py:154} INFO - Started process (PID=2438) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:06:16.399+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:06:16.400+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:06:16.399+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:06:16.592+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:06:16.591+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:06:16.593+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:06:16.620+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.227 seconds
[2022-11-23T09:06:47.172+0000] {processor.py:154} INFO - Started process (PID=2494) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:06:47.175+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:06:47.176+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:06:47.176+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:06:47.367+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:06:47.366+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:06:47.368+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:06:47.422+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.254 seconds
[2022-11-23T09:07:17.884+0000] {processor.py:154} INFO - Started process (PID=2552) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:07:17.885+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:07:17.886+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:07:17.886+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:07:18.118+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:07:18.117+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:07:18.119+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:07:18.177+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.298 seconds
[2022-11-23T09:07:48.213+0000] {processor.py:154} INFO - Started process (PID=2617) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:07:48.214+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:07:48.216+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:07:48.215+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:07:48.412+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:07:48.411+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:07:48.412+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:07:48.465+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.257 seconds
[2022-11-23T09:08:18.948+0000] {processor.py:154} INFO - Started process (PID=2672) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:08:18.949+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:08:18.950+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:08:18.950+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:08:19.223+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:08:19.221+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:08:19.235+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:08:19.308+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.364 seconds
[2022-11-23T09:08:49.453+0000] {processor.py:154} INFO - Started process (PID=2728) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:08:49.454+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:08:49.455+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:08:49.455+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:08:49.680+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:08:49.678+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:08:49.680+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:08:49.705+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.256 seconds
[2022-11-23T09:09:20.251+0000] {processor.py:154} INFO - Started process (PID=2794) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:09:20.252+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:09:20.252+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:09:20.252+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:09:20.428+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:09:20.427+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:09:20.428+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:09:20.464+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.218 seconds
[2022-11-23T09:09:51.127+0000] {processor.py:154} INFO - Started process (PID=2849) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:09:51.129+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:09:51.130+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:09:51.130+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:09:51.311+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:09:51.311+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:09:51.312+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:09:51.341+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.218 seconds
[2022-11-23T09:10:21.759+0000] {processor.py:154} INFO - Started process (PID=2914) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:10:21.761+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:10:21.762+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:10:21.762+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:10:22.002+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:10:22.001+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:10:22.003+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:10:22.061+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.306 seconds
[2022-11-23T09:10:52.243+0000] {processor.py:154} INFO - Started process (PID=2970) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:10:52.245+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:10:52.246+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:10:52.246+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:10:52.420+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:10:52.419+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:10:52.421+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:10:52.452+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.213 seconds
[2022-11-23T09:11:23.022+0000] {processor.py:154} INFO - Started process (PID=3035) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:11:23.026+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:11:23.027+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:11:23.027+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:11:23.195+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:11:23.194+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:11:23.196+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:11:23.223+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.205 seconds
[2022-11-23T09:11:53.824+0000] {processor.py:154} INFO - Started process (PID=3092) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:11:53.826+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:11:53.827+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:11:53.827+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:11:54.012+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:11:54.010+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:11:54.013+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:11:54.047+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.227 seconds
[2022-11-23T09:12:24.461+0000] {processor.py:154} INFO - Started process (PID=3156) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:12:24.462+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:12:24.463+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:12:24.463+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:12:24.645+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:12:24.644+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:12:24.645+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:12:24.671+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.215 seconds
[2022-11-23T09:12:55.043+0000] {processor.py:154} INFO - Started process (PID=3211) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:12:55.045+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:12:55.046+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:12:55.045+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:12:55.288+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:12:55.271+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:12:55.289+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:12:55.361+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.322 seconds
[2022-11-23T09:13:26.093+0000] {processor.py:154} INFO - Started process (PID=3275) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:13:26.099+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:13:26.101+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:13:26.100+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:13:26.420+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:13:26.419+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:13:26.420+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:13:26.448+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.360 seconds
[2022-11-23T09:13:56.733+0000] {processor.py:154} INFO - Started process (PID=3330) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:13:56.735+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:13:56.736+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:13:56.736+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:13:56.896+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:13:56.894+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:13:56.896+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:13:56.924+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.195 seconds
[2022-11-23T09:14:27.511+0000] {processor.py:154} INFO - Started process (PID=3395) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:14:27.512+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:14:27.513+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:14:27.513+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:14:27.710+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:14:27.709+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:14:27.710+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:14:27.763+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.256 seconds
[2022-11-23T09:14:58.504+0000] {processor.py:154} INFO - Started process (PID=3451) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:14:58.506+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:14:58.507+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:14:58.507+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:14:58.672+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:14:58.671+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:14:58.672+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:14:58.703+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.203 seconds
[2022-11-23T09:15:29.127+0000] {processor.py:154} INFO - Started process (PID=3516) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:15:29.128+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:15:29.130+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:15:29.129+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:15:29.312+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:15:29.310+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:15:29.312+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:15:29.348+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.226 seconds
[2022-11-23T09:15:59.549+0000] {processor.py:154} INFO - Started process (PID=3573) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:15:59.551+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:15:59.552+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:15:59.552+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:15:59.734+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:15:59.733+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:15:59.735+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:15:59.761+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.216 seconds
[2022-11-23T09:16:30.687+0000] {processor.py:154} INFO - Started process (PID=3638) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T09:16:30.689+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T09:16:30.690+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:16:30.690+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:16:30.875+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:16:30.874+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:16:30.875+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T09:16:30.901+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.218 seconds
[2022-11-23T11:05:26.439+0000] {processor.py:154} INFO - Started process (PID=42) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T11:05:26.441+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T11:05:26.442+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:05:26.441+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T11:05:26.716+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:05:26.714+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T11:05:26.716+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T11:05:26.748+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.318 seconds
[2022-11-23T11:05:56.826+0000] {processor.py:154} INFO - Started process (PID=100) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T11:05:56.827+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T11:05:56.828+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:05:56.828+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T11:05:57.018+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:05:57.016+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T11:05:57.018+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T11:05:57.041+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.218 seconds
[2022-11-23T11:06:27.509+0000] {processor.py:154} INFO - Started process (PID=156) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T11:06:27.517+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T11:06:27.519+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:06:27.519+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T11:06:27.732+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:06:27.731+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T11:06:27.733+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T11:06:27.789+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.289 seconds
[2022-11-23T11:06:58.070+0000] {processor.py:154} INFO - Started process (PID=221) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T11:06:58.071+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T11:06:58.073+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:06:58.072+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T11:06:58.340+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:06:58.339+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T11:06:58.341+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T11:06:58.371+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.306 seconds
[2022-11-23T11:07:28.929+0000] {processor.py:154} INFO - Started process (PID=276) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T11:07:28.930+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T11:07:28.931+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:07:28.931+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T11:07:29.078+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:07:29.077+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T11:07:29.079+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T11:07:29.095+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.171 seconds
[2022-11-23T12:41:40.121+0000] {processor.py:154} INFO - Started process (PID=34) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T12:41:40.128+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T12:41:40.129+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:41:40.128+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T12:41:40.318+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:41:40.317+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T12:41:40.319+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T12:41:40.356+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.242 seconds
[2022-11-23T12:42:11.207+0000] {processor.py:154} INFO - Started process (PID=99) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T12:42:11.208+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T12:42:11.209+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:42:11.209+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T12:42:11.354+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:42:11.353+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T12:42:11.355+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T12:42:11.379+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.175 seconds
[2022-11-23T12:42:42.383+0000] {processor.py:154} INFO - Started process (PID=166) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T12:42:42.385+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T12:42:42.386+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:42:42.385+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T12:42:42.559+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:42:42.558+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T12:42:42.559+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T12:42:42.586+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.209 seconds
[2022-11-23T12:43:12.860+0000] {processor.py:154} INFO - Started process (PID=222) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T12:43:12.861+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T12:43:12.862+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:43:12.862+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T12:43:12.988+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:43:12.987+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T12:43:12.988+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T12:43:13.009+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.152 seconds
[2022-11-23T12:43:43.764+0000] {processor.py:154} INFO - Started process (PID=287) to work on /opt/airflow/dags/queue_reader.py
[2022-11-23T12:43:43.765+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-23T12:43:43.766+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:43:43.766+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-23T12:43:43.892+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:43:43.891+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T12:43:43.893+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-23T12:43:43.916+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.155 seconds
